//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressConfig
    {
        public System.Guid id { get; set; }
        public System.Guid parentId { get; set; }
        public string Content { get; set; }
        public int layer { get; set; }
    }
}
