//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid id { get; set; }
        public System.Guid accountId { get; set; }
        public string Address1 { get; set; }
        public string tel { get; set; }
        public string name { get; set; }
        public Nullable<bool> defaultAddress { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
