//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsDetail
    {
        public System.Guid id { get; set; }
        public string imageName { get; set; }
        public string introduce { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
