//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.MealsDetails = new HashSet<MealsDetail>();
            this.MealsOrderDetails = new HashSet<MealsOrderDetail>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string imangeName { get; set; }
        public decimal totalPrice { get; set; }
        public int sellCount { get; set; }
        public int stock { get; set; }
        public Nullable<byte> evaluate { get; set; }
        public System.DateTime createTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealsDetail> MealsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealsOrderDetail> MealsOrderDetails { get; set; }
    }
}
