//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealsDetail
    {
        public System.Guid id { get; set; }
        public System.Guid mealsId { get; set; }
        public System.Guid goodsId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
