//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealsOrderDetail
    {
        public System.Guid id { get; set; }
        public System.Guid mealsOrderId { get; set; }
        public System.Guid mealsId { get; set; }
        public int count { get; set; }
        public decimal price { get; set; }
        public Nullable<byte> evaluate { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual MealsOrder MealsOrder { get; set; }
    }
}
